INCFLAGS += -I$(CORE_DIR)

SOURCES_CXX := \
	$(CORE_DIR)/Common.cpp \
	$(CORE_DIR)/Database.cpp \
	$(CORE_DIR)/libretro.cpp

SOURCES_C := \
	$(CORE_DIR)/Bios.c \
	$(CORE_DIR)/Cartridge.c \
	$(CORE_DIR)/Hash.c \
	$(CORE_DIR)/Maria.c \
	$(CORE_DIR)/Memory.c \
	$(CORE_DIR)/Palette.c \
	$(CORE_DIR)/Pokey.c \
	$(CORE_DIR)/ProSystem.c \
	$(CORE_DIR)/Region.c \
	$(CORE_DIR)/Riot.c \
	$(CORE_DIR)/Sally.c \
	$(CORE_DIR)/Tia.c
